// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsmBT4vIbowLSXl7TdJCcnVxp0b6J828E',
    appId: '1:39472394989:web:a07a2a44238c09cbb592e4',
    messagingSenderId: '39472394989',
    projectId: 'appoff-54417961',
    authDomain: 'appoff-54417961.firebaseapp.com',
    storageBucket: 'appoff-54417961.firebasestorage.app',
    measurementId: 'G-XRKYB49DV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzBer4JMytTyeCALSSpbYw0t8r6Mj6lvE',
    appId: '1:39472394989:android:12e08262b6df0fa0b592e4',
    messagingSenderId: '39472394989',
    projectId: 'appoff-54417961',
    storageBucket: 'appoff-54417961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC194Cu0_aIlj0XohmY49OKh7UxUviKTBQ',
    appId: '1:39472394989:ios:d203ee142ed22661b592e4',
    messagingSenderId: '39472394989',
    projectId: 'appoff-54417961',
    storageBucket: 'appoff-54417961.firebasestorage.app',
    iosBundleId: 'com.example.appoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC194Cu0_aIlj0XohmY49OKh7UxUviKTBQ',
    appId: '1:39472394989:ios:d203ee142ed22661b592e4',
    messagingSenderId: '39472394989',
    projectId: 'appoff-54417961',
    storageBucket: 'appoff-54417961.firebasestorage.app',
    iosBundleId: 'com.example.appoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsmBT4vIbowLSXl7TdJCcnVxp0b6J828E',
    appId: '1:39472394989:web:1e87ed3efe28496cb592e4',
    messagingSenderId: '39472394989',
    projectId: 'appoff-54417961',
    authDomain: 'appoff-54417961.firebaseapp.com',
    storageBucket: 'appoff-54417961.firebasestorage.app',
    measurementId: 'G-TW6CC8K9VK',
  );
}
